# Tensorflow V1

In [1]:
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


### Basic Syntax

In [8]:
hello = tf.constant("Hello ")
world = tf.constant("World")

with tf.Session() as session:
    result = session.run(hello + world)
    
result

b'Hello World'

In [9]:
a = tf.constant(10)
b = tf.constant(20)

with tf.Session() as session:
    result = session.run(a + b)
    
result

30

In [19]:
dims = (4,4)
fill_mat = tf.fill(dims, 10)
my_zeros = tf.zeros(dims)
my_ones = tf.ones(dims)
my_randn = tf.random_normal(dims, mean=0, stddev=1.0)
my_randu = tf.random_uniform(dims, minval=0, maxval=1.0)

my_ops = [fill_mat, my_zeros, my_ones, my_randn, my_randu]

In [24]:
with tf.Session() as session:
    for op in my_ops:
        print(f"{session.run(op)}\n\n")

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-1.6001428  -1.2634546  -2.0745387   0.09527214]
 [ 0.32760695  0.00628623 -0.33167526  0.9310093 ]
 [-0.02907251 -1.9944315   1.7737905   0.55147856]
 [-0.4108656   0.7113938   0.9342754  -0.8850058 ]]


[[0.02766407 0.4562949  0.29201257 0.329836  ]
 [0.58456016 0.6072509  0.77950215 0.9817246 ]
 [0.1739167  0.10640609 0.6376312  0.9841075 ]
 [0.36370862 0.4930657  0.6949791  0.8797965 ]]




In [28]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[10],[100]])

a.get_shape(), b.get_shape()

(TensorShape([Dimension(2), Dimension(2)]),
 TensorShape([Dimension(2), Dimension(1)]))

In [30]:
with tf.Session() as session:
    result = session.run(tf.matmul(a, b))

result

array([[210],
       [430]])

### Graph

In [3]:
n1 = tf.constant(1)
n2 = tf.constant(2)

n3 = n1 + n2

with tf.Session() as session:
    result = session.run(n3)
    
result

3

In [4]:
print(tf.get_default_graph())

In [7]:
g = tf.Graph()

print(g)

In [8]:
graph_1 = tf.get_default_graph()
graph_2 = tf.Graph()

In [10]:
with graph_2.as_default():
    print(graph_2 is tf.get_default_graph())

True


In [11]:
my_tensor = tf.random.uniform((4,4), 0, 1)
my_var = tf.Variable(initial_value=my_tensor)

print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [19]:
with tf.Session() as session:
    init = tf.global_variables_initializer()
    session.run(init)
    result = session.run(my_var)
    
result

array([[0.75570154, 0.7910776 , 0.31299126, 0.4479246 ],
       [0.55835557, 0.7520344 , 0.07806861, 0.68039715],
       [0.0202086 , 0.80994344, 0.8603116 , 0.22186112],
       [0.6182276 , 0.05153227, 0.19410264, 0.41053784]], dtype=float32)

In [20]:
ph = tf.placeholder(tf.float32, shape=(None, 5))